function P = starch_parameter_call(starch_mutant)
%% loads the parameters for the starch model, according to the specified genotype
%
% Input:
%   starch_mutant - a structure containing strings specifying the genotype (e.g. {'lsf1'} for the lsf1 mutant)
%
% Output:
%   P - a structure of named parameters for the starch model

P = struct(...
    'ksY', 1, ...
    'kdY', 0.02, ...
    'ksS', 2, ...
    'KsS', 100, ...
    'kdS', 20, ...
    'KdS', 0.5,...
    'KdSX', 100,...
    'ksX', 40, ...
    'kdX', 100, ...
    'ksT1', 7.5, ...
    'ksT2', 11.2, ...
    'KsT2',0.512, ...
    'kdT1', 14.5, ...
    'kdT2', 0.06, ...
    'KdT2', 0.003, ...
    'turnover_override', false, ...
    'turnover', nan ...
    );

for i = 1:length(starch_mutant)
    if strcmp(starch_mutant{i},'LSF1') || strcmp(starch_mutant{i},'lsf1')
        %P.kdstarch = 0.2*P.kdstarch;
        P.kdS = 10;
        P.kdT2 = P.kdT2*0.3;
    end
end
