function P = starch_parameter_call(starch_mutant)
%% loads the parameters for the starch model, according to the specified genotype
%
% Input:
%   starch_mutant - a structure containing strings specifying the genotype (e.g. {'lsf1'} for the lsf1 mutant)
%
% Output:
%   P - a structure of named parameters for the starch model
%
%   Copyright 2018 Yin Hoon Chew, Daniel Seaton, Andrew Millar, and The University of Edinburgh
%
%   Licensed under the Apache License, Version 2.0 (the "License");
%   you may not use this file except in compliance with the License.
%   You may obtain a copy of the License at
%
%       http://www.apache.org/licenses/LICENSE-2.0
%
%   Unless required by applicable law or agreed to in writing, software
%   distributed under the License is distributed on an "AS IS" BASIS,
%   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%   See the License for the specific language governing permissions and
%   limitations under the License.
  
P = struct(...
    'ksY', 1, ...
    'kdY', 0.02, ...
    'ksS', 2, ...
    'KsS', 100, ...
    'kdS', 20, ...
    'KdS', 0.5,...
    'KdSX', 100,...
    'ksX', 40, ...
    'kdX', 100, ...
    'ksT1', 7.5, ...
    'ksT2', 11.2, ...
    'KsT2',0.512, ...
    'kdT1', 14.5, ...
    'kdT2', 0.06, ...
    'KdT2', 0.003, ...
    'turnover_override', false, ...
    'turnover', nan ...
    );

for i = 1:length(starch_mutant)
    if strcmp(starch_mutant{i},'LSF1') || strcmp(starch_mutant{i},'lsf1')
        %P.kdstarch = 0.2*P.kdstarch;
        P.kdS = 10;
        P.kdT2 = P.kdT2*0.3;
    end
end
