function P = starch_parameter_call(starch_mutant)

P = struct(...
    'ksY', 1, ...
    'kdY', 0.02, ...
    'ksS', 2, ...
    'KsS', 100, ...
    'kdS', 20, ...
    'KdS', 0.5,...
    'KdSX', 100,...
    'ksX', 40, ...
    'kdX', 100, ...
    'ksT1', 7.5, ...
    'ksT2', 14, ...
    'KsT2',0.4, ...
    'kdT1', 14.5, ...
    'kdT2', 0.06, ...
    'KdT2', 0.003 ...
    );

for i = 1:length(starch_mutant)
    if strcmp(starch_mutant{i},'SEX')
        %P.kdstarch = 0.2*P.kdstarch;
        P.kdS = 1*P.kdS;
    end
    
    if strcmp(starch_mutant{i},'LSF1')
        %P.kdstarch = 0.2*P.kdstarch;
        P.kdS = 10;
        P.kdT2 = P.kdT2*0.3;
        
    end
    
    if strcmp(starch_mutant{i},'H_L')
        %high light
        P.vstarch = 1.5*P.vstarch;
    end
    
    if strcmp(starch_mutant{i},'L_L')
        %low light
        P.vstarch = 0.5*P.vstarch;
    end
end